export { inPortal } from './lib/helpers'
export { usePortalClient } from './lib/usePortalClient'
export { usePortalService } from './lib/usePortalService'

export type { Badge } from './lib/types/Badge'
export type { Message } from './lib/types/Message'
export type { NotificationMessage } from './lib/types/NotificationMessage'
export type { PortalBase } from './lib/types/PortalBase'
export type { PortalClient } from './lib/types/PortalClient'
export type { PortalService } from './lib/types/PortalService'
export type { Resource } from './lib/types/Resource'
export type { Session } from './lib/types/Session'
export type { StoreOptions } from './lib/types/StoreOptions'
export type { User } from './lib/types/User'
export type { Workspace } from './lib/types/Workspace'

export const VERSION = __APP_VERSION__
export { $, connectToTarget, uuid } from '@orango/beam-client'
export { CONNECTION } from '@orango/beam-client'
export { WINDOW } from '@orango/beam-client'
export { NETWORK } from '@orango/beam-client'
export { ELEMENT } from '@orango/beam-client'
export { ELEMENTS } from '@orango/beam-client'
export { FORM } from '@orango/beam-client'
export { INPUT } from '@orango/beam-client'
export { APP } from './lib/consts/app'
export { NOTIFICATION } from './lib/consts/notification'
export { RESOURCE } from './lib/consts/resource'
export { SESSION } from './lib/consts/session'
export { SYSTEM } from './lib/consts/system'
export { STORE } from './lib/consts/store'
export { USER } from './lib/consts/user'
